### ISSUE TITLE
Window resize issue

### ISSUE THREAD

**Issue by Wojciech-Nowocien** [JLi69/terratest#2]
# View space issue

Changing the window size affects the size of the field of view. In the first photo we see one tree on the left. The second one has two and the third one has three. The size of the window should not determine the field of view.

![screenshot 2024-03-02 221300](https://github.com/JLi69/terratest/assets/93791743/2fbcff05-c8ba-488a-976f-66ecb4d2e3cc)
![screenshot 2024-03-02 221330](https://github.com/JLi69/terratest/assets/93791743/2009af76-9265-47c7-b07a-0c3722b6587a)
![screenshot 2024-03-02 221527](https://github.com/JLi69/terratest/assets/93791743/cd1b2150-2922-4f4d-b4ee-354f4d4f9250)

**Comment by JLi69** [comment]
Making the window size affect the field of view was a deliberate design choice.
This is a two dimensional game and I figured that would have been acceptable but I suppose that having a consistent FOV would make more sense, I will see what I can do.

**Comment by JLi69** [comment]
Alright, I made it so that whenever you resize the window, the display will instead attempt to scale up or down rather than shrink/expand the FOV. The GUI still retains the same size whenever the window is resized though. Do you have any other suggestions?

**Comment by Wojciech-Nowocien** [comment]
The easiest way to fix this is to disable window resize using `glfwSetWindowAttrib(win, GLFW_RESIZABLE, 0);`, but this is not a very good option. You can implement an orthographic camera and use the window size aspect to update the camera matrix. This would be the best solution, but it would take some time and work.

**Comment by JLi69** [comment]
I have implemented your suggestion in this [commit](https://github.com/JLi69/terratest/commit/6e1675f2f976d756be7d75b495e015d5ee251a56)

In all due honesty, I have realized that much of the code I have written for this project isn't particularly good and the change I have made is rather hacky but should hopefully work for now. Please let me know of any other thoughts you currently have on this, and if all is good I'll close the issue.
